# Generated by Django 3.1.5 on 2021-01-22 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boletim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagInicial', models.IntegerField()),
                ('pagFinal', models.IntegerField()),
                ('aprovado', models.BooleanField(default=False)),
                ('assinado', models.BooleanField(default=False)),
                ('numeroBI', models.IntegerField()),
                ('assinaConfereBI', models.BooleanField(default=False)),
                ('dataPub', models.DateField()),
                ('slug', models.SlugField()),
            ],
        ),
    ]
