# Generated by Django 3.1.5 on 2021-01-24 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParteBoletim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_Parte', models.IntegerField()),
                ('descricao', models.CharField(max_length=250)),
                ('descricao_Reduzida', models.CharField(max_length=250)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='SecaoParteBoletim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_Secao', models.IntegerField()),
                ('descricao', models.CharField(max_length=250)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoBoletim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=250)),
                ('abreviatura', models.CharField(max_length=250)),
                ('numero_Ultima_Pagina', models.IntegerField()),
                ('numero_Ultimo_Boletim', models.IntegerField()),
                ('inicia_Numero_Pagina', models.IntegerField()),
                ('e_Aditamento', models.BooleanField()),
                ('imprime_Bordas', models.BooleanField()),
                ('titulo', models.CharField(max_length=250)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Boletim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagina_Inicial', models.IntegerField()),
                ('pagina_Final', models.IntegerField()),
                ('aprovado', models.BooleanField(default=False)),
                ('assinado', models.BooleanField(default=False)),
                ('numero_Boletim', models.IntegerField()),
                ('assina_ConfereBoletim', models.BooleanField(default=False)),
                ('data_Publicacao', models.DateField()),
                ('slug', models.SlugField()),
                ('boletim_De_Referencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boletim.boletim')),
                ('tipo_Boletim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boletim.tipoboletim')),
            ],
        ),
    ]
