# Generated by Django 3.1.5 on 2021-01-23 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParteBoletim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroParte', models.IntegerField()),
                ('descricao', models.CharField(max_length=250)),
                ('descricaoReduzida', models.CharField(max_length=250)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='SecaoParteBoletim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroSecao', models.IntegerField()),
                ('descricao', models.CharField(max_length=250)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoBoletim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=250)),
                ('abreviatura', models.CharField(max_length=250)),
                ('slug', models.SlugField()),
                ('numeroUltimaPagina', models.IntegerField()),
                ('numeroUltimoBoletim', models.IntegerField()),
                ('iniciaNumeroPagina', models.IntegerField()),
                ('eAditamento', models.BooleanField()),
                ('imprimeBordas', models.BooleanField()),
                ('titulo', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Boletim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paginaInicial', models.IntegerField()),
                ('paginaFinal', models.IntegerField()),
                ('aprovado', models.BooleanField(default=False)),
                ('assinado', models.BooleanField(default=False)),
                ('numeroBoletim', models.IntegerField()),
                ('assinaConfereBoletim', models.BooleanField(default=False)),
                ('dataPublicacao', models.DateField()),
                ('slug', models.SlugField()),
                ('boletimDeReferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boletim.boletim')),
                ('tipoBoletim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boletim.tipoboletim')),
            ],
        ),
    ]
