# Generated by Django 3.1.5 on 2021-01-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizacaoMilitar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('sigla', models.CharField(max_length=250)),
                ('designacao_Historica', models.CharField(max_length=250)),
                ('subordinacao_1', models.CharField(max_length=250)),
                ('sobordinacao_2', models.CharField(max_length=250)),
                ('subordinacao_3', models.CharField(max_length=250)),
                ('subordinacao_4', models.CharField(max_length=250)),
                ('guarnicao', models.CharField(max_length=250)),
                ('codom', models.IntegerField(unique=True)),
                ('ano_Corrente', models.IntegerField(choices=[(1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], default=2021)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identidade', models.CharField(max_length=250)),
                ('funcao', models.CharField(max_length=250)),
                ('nome_Completo', models.CharField(max_length=250)),
                ('nome_Guerra', models.CharField(max_length=250)),
                ('sexo', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('N', 'Nenhuma das opções')], max_length=1)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
