# Generated by Django 3.1.5 on 2021-01-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identidade', models.CharField(max_length=250)),
                ('funcao', models.CharField(max_length=250)),
                ('nome_Completo', models.CharField(max_length=250)),
                ('nome_Guerra', models.CharField(max_length=250)),
                ('slug', models.SlugField()),
                ('sexo', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('N', 'Nenhuma das opções')], max_length=1)),
            ],
        ),
    ]
