# Generated by Django 3.1.5 on 2021-01-23 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boletim', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssuntoEspecifico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('vaiIndice', models.BooleanField()),
                ('textoPadraoAbertura', models.TextField()),
                ('vaiAlteracao', models.BooleanField()),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='AssuntoGeral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('parteBoletim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boletim.parteboletim')),
                ('secaoParteBoletim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boletim.secaoparteboletim')),
                ('tipoBoletim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boletim.tipoboletim')),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('textoAbertura', models.TextField()),
                ('textoFechamento', models.TextField()),
                ('numeroDocumento', models.IntegerField()),
                ('vaiAlteracao', models.BooleanField()),
                ('aprovada', models.BooleanField()),
                ('dataDocumento', models.DateField()),
                ('pagina', models.IntegerField()),
                ('slug', models.SlugField()),
                ('assuntoEspecifico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materia.assuntoespecifico')),
                ('assuntoGeral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materia.assuntogeral')),
                ('tipoBoletim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boletim.tipoboletim')),
                ('tipoDocumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materia.tipodocumento')),
            ],
        ),
    ]
