# Generated by Django 3.1.5 on 2021-01-23 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boletim', '0001_initial'),
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssuntoEspecifico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('vai_Indice', models.BooleanField()),
                ('texto_PadraoAbertura', models.TextField()),
                ('vai_Alteracao', models.BooleanField()),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='AssuntoGeral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('parte_Boletim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boletim.parteboletim')),
                ('secao_ParteBoletim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boletim.secaoparteboletim')),
                ('tipo_Boletim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boletim.tipoboletim')),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='PessoaMateriaBoletim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_Individual', models.TextField()),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('texto_Abertura', models.TextField()),
                ('texto_Fechamento', models.TextField()),
                ('numero_Documento', models.IntegerField()),
                ('vai_Alteracao', models.BooleanField()),
                ('aprovada', models.BooleanField()),
                ('data_Documento', models.DateField()),
                ('pagina', models.IntegerField()),
                ('slug', models.SlugField()),
                ('texto_FechamentoVaiAlteracao', models.BooleanField(default=False)),
                ('ordem_Materia', models.IntegerField()),
                ('assunto_Especifico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materia.assuntoespecifico')),
                ('assunto_Geral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materia.assuntogeral')),
                ('tipo_Boletim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boletim.tipoboletim')),
                ('tipo_Documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materia.tipodocumento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
